### ISSUE TITLE
Publishing v1.2.0 to Dockerhub failed

### ISSUE THREAD

**Issue by axdotl** [backstage/techdocs-container#50]
The build step to publish release `v1.2.0` to Dockerhub failed with error message:
```
ERROR: failed to solve: failed to push spotify/techdocs:latest: server message: insufficient_scope: authorization failed
```

As a result `v1.2.0` is not available and can not be used. 
See [workflow run](https://github.com/backstage/techdocs-container/actions/runs/4598579825/jobs/8122804901) for details.

**Edit**: Found a related PR in draft, see
- #49

**Comment by agentbellnorm** [comment]
@axdotl `v1.2.0` is available on [dockerhub](https://hub.docker.com/r/spotify/techdocs/tags) now. Once #52 is merged `latest` should also be up to date.

Closing this issue, let us know if you encounter any issues!
