### ISSUE TITLE
Please update PlantUML to latest version (1.2024.4 as of now)

### ISSUE THREAD

**Issue by pwretmo** [backstage/techdocs-container#68]
Newer standard libraries such as K8s is missing in currently used version (1.2023.10) of  PlantUML.

Please update plantuml.jar in docker image to latest version (1.2024.4).

https://github.com/backstage/techdocs-container/blob/e61e092f1dce41ed6d177ef1814169c55ecb6c9f/Dockerfile#L20

**Comment by pwalleni** [comment]
Hi @pwretmo. Thanks for pointing it out. FYI: https://github.com/volvo-cars/techdocs-workflows/pull/85/files#diff-d0777657fa3fd81d23aaf7273e58aee453b04e67882517900c56daeef9b3e4c1R325

**Comment by awanlin** [comment]
Got a PR open to do this 👍
